### PR TITLE
Add song download

### PR DESCRIPTION
**Pull request by jeydinpham**
Added song download link cause why not .-.

### CODE REVIEW

**Comment by Tomato6966** [comment]
just do song.streamURL and then click on the result ...

**Comment by jeydinpham** [comment]
Then it would send this giant link .-.
Doing it as [Download This Link](${song.streamURL}) is more visually
appealing ;-;

**Comment by Tomato6966** [comment]
I didnt told you how to do  a format just how to get the download url .-.

**Comment by jeydinpham** [comment]
Wat

**Pull request closed without merging**
